import equational_theories.MagmaLaw
import equational_theories.Equations.Command
import VersoBlog

open Verso Genre Blog

#doc (Page) "Equations and Laws" =>

# Reasoning about syntax

- The metatheorems are based on *syntactic* properties of the equations under consideration.

- However, this kind of reasoning about syntax is impossible to do directly within Lean.

- For example, consider the definition

```leanInit equationsAndLaws
namespace EquationsAndLaws
```

```lean equationsAndLaws
def n : Nat := 1 + 2
```

- It's impossible to directly prove that this definition of `n` contains exactly five characters
  (including spaces), because otherwise it would be possible to prove that `1 + 2 ≠ 3` by comparing character lengths.

- Performing this kind of reasoning requires access to an object representing the underlying syntax of the expression,
  together with a proof that certain kinds of reasoning done with this object can be translated into results about the original equation.

# Equations and laws

- The project makes a distinction between *equations* and *laws*.

- An *equation* is a statement such as

```lean equationsAndLaws
equation 953  :=  x = y ◇ ((z ◇ x) ◇ (z ◇ z))

@[reducible] def Equation953' (G : Type u) [Magma G] : Prop :=
  ∀ (x y z : G), x = y ◇ ((z ◇ x) ◇ (z ◇ z))
```

that is a universally quantified equation over magmas regarding which theorems are proved.

- A *law* is a statement such as

```lean equationsAndLaws
def Law953' : Law.NatMagmaLaw :=
Lf 0 ≃ Lf 1 ⋆ (Lf 2 ⋆ Lf 0 ⋆ (Lf 2 ⋆ Lf 2))
```

that represents the syntactic form of an equation. Laws are usually defined with respect to a fixed set of variables (the "alphabet").

- Laws can be defined as pairs of words in the free magma over a given alphabet

```lean equationsAndLaws
structure MagmaLaw (α : Type*) where
  lhs : FreeMagma α
  rhs : FreeMagma α
deriving DecidableEq

infix:60 " ≃ " => MagmaLaw.mk

abbrev NatMagmaLaw := MagmaLaw Nat
```

- It is possible to define when a magma satisfies a given law

```lean equationsAndLaws
namespace EquationsAndLaws

/-- Definitions of entailment -/
def satisfiesPhi {α G} [Magma G] (φ : α → G) (E : MagmaLaw α) : Prop :=
  E.lhs ⬝ φ = E.rhs ⬝ φ

/-- `satisfies G E`, or `G ⊧ E`, means that all evaluations of `E` in `G` are true. -/
def satisfies {α} (G) [Magma G] (E : MagmaLaw α) := ∀ (φ : α → G), satisfiesPhi φ E

end EquationsAndLaws
```

# Generating proofs of equivalence

- When an equation is defined, we would like to automatically generate the corresponding law,
  together with a proof that a magma satisfies a law iff the equation holds in that magma.

- Equations in this project are defined using the `equation` command (written by Joachim Breitner).

```lean equationsAndLaws
equation 2662  :=  x = ((x ◇ y) ◇ (x ◇ y)) ◇ x
```

- This automatically generates an expanded definition in the environment.

```lean equationsAndLaws
#print Equation2662

-- this is the expanded definition of the equation that gets stored in the environment
@[reducible] def Equation2662' (G : Type u) [Magma G] : Prop :=
  ∀ (x y : G), x = ((x ◇ y) ◇ (x ◇ y)) ◇ x
```

- The command has access to the syntax of the equation being defined, so it can be extended to
  also generate the corresponding law in the process.

```lean equationsAndLaws
#print Law2662

-- this definition is automatically generated by the `equation` command
def Law2662' : Law.NatMagmaLaw :=
Lf 0 ≃ Lf 0 ⋆ Lf 1 ⋆ (Lf 0 ⋆ Lf 1) ⋆ Lf 0
```

- The command can also be extended to automatically generates a proof
  that a magma satisfies the law if and only if it satisfies the equation.

```lean equationsAndLaws
-- `Law2662.models_iff.{u} (G : Type u) [inst : Magma G] : G ⊧ Law2662 ↔ Equation2662 G`
#check Law2662.models_iff
```

- Roughly, the recipe is to show that any choice of quantified variables `x₁, x₂, ...` in the equation
  can be mapped to a corresponding evaluation of the law in the magma, and vice versa.
  This is more conveniently done with a version of the law where the variable set is finite and matches the number of quantified variables in the equation.
  The definitions are set up so that the result of evaluating a law is definitionally equal to the original equation.

- This set-up has since been modified and strengthened by Mario Carneiro.
