name: Propose PR

on:
  issue_comment:
    types: [created]

jobs:
  propose_pr:
    if: github.event.issue.pull_request == null && contains(github.event.comment.body, 'propose')
    runs-on: ubuntu-latest

    steps:
    - name: Check if the comment contains "propose #PR_NUMBER"
      id: check_propose
      run: |
        COMMENT_BODY="${{ github.event.comment.body }}"
        COMMENT_BODY_LOWER=$(echo "$COMMENT_BODY" | tr '[:upper:]' '[:lower:]')

        # Use a refined regex with [[:space:]] to match any whitespace
        if [[ "$COMMENT_BODY_LOWER" =~ propose[[:space:]]*(pr[[:space:]]*)?\#([0-9]+)[[:space:]]* ]]; then
          PR_NUMBER="${BASH_REMATCH[2]}"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV
        else
          echo "The comment does not contain a valid 'propose #PR_NUMBER' format."
          exit 1
        fi

    - name: Get issue details
      id: get_issue
      run: |
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} > issue.json
        cat issue.json

    - name: Check if the commenter is assigned to the issue
      id: check_assignee
      run: |
        COMMENTER="${{ github.event.comment.user.login }}"
        ASSIGNED=$(jq --arg user "$COMMENTER" '.assignees[]?.login | select(. == $user)' issue.json)
        if [ -z "$ASSIGNED" ]; then
          echo "not_assigned=true" >> $GITHUB_ENV
        else
          echo "not_assigned=false" >> $GITHUB_ENV
        fi

    - name: Notify the user if they are not assigned
      if: env.not_assigned == 'true'
      run: |
        echo "User ${{ github.event.comment.user.login }} is not assigned to this issue, exiting."
        exit 0

    - name: Get the PR node_id using GraphQL
      id: get_pr_node_id
      run: |
        QUERY=$(jq -n --arg owner "${{ github.repository_owner }}" --arg name "${{ github.event.repository.name }}" --arg number "${{ env.pr_number }}" \
          '{"query": "query { repository(owner: \($owner), name: \($name)) { pullRequest(number: \($number)) { id } } }"}')

        echo "Sending query: $QUERY"

        RESPONSE=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data "$QUERY" https://api.github.com/graphql)

        echo "PR Node ID Response: $RESPONSE"
        PR_NODE_ID=$(echo "$RESPONSE" | jq -r '.data.repository.pullRequest.id')

        if [ -z "$PR_NODE_ID" ]; then
          echo "Error: Could not retrieve PR node_id"
          exit 1
        else
          echo "PR_NODE_ID=$PR_NODE_ID" >> $GITHUB_ENV
        fi

    - name: Get the Issue node_id using GraphQL
      id: get_issue_node_id
      run: |
        QUERY=$(jq -n --arg owner "${{ github.repository_owner }}" --arg name "${{ github.event.repository.name }}" --arg number "${{ github.event.issue.number }}" \
          '{"query": "query { repository(owner: \($owner), name: \($name)) { issue(number: \($number)) { id } } }"}')

        echo "Sending query: $QUERY"

        RESPONSE=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data "$QUERY" https://api.github.com/graphql)

        echo "Issue Node ID Response: $RESPONSE"
        ISSUE_NODE_ID=$(echo "$RESPONSE" | jq -r '.data.repository.issue.id')

        if [ -z "$ISSUE_NODE_ID" ]; then
          echo "Error: Could not retrieve issue node_id"
          exit 1
        else
          echo "ISSUE_NODE_ID=$ISSUE_NODE_ID" >> $GITHUB_ENV
        fi

    - name: Link PR to the issue using GraphQL
      id: link_pr_to_issue
      if: env.not_assigned == 'false'
      run: |
        QUERY=$(jq -n --arg pr_id "${{ env.PR_NODE_ID }}" --arg issue_id "${{ env.ISSUE_NODE_ID }}" \
          '{"query": "mutation { addPullRequestToIssue(input: {issueId: \($issue_id), pullRequestId: \($pr_id)}) { issue { id } } }"}')

        echo "Sending mutation: $QUERY"

        RESPONSE=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data "$QUERY" https://api.github.com/graphql)

        echo "GraphQL Mutation Response: $RESPONSE"
        SUCCESS=$(echo "$RESPONSE" | jq -r '.data.addPullRequestToIssue.issue.id')

        if [ -z "$SUCCESS" ]; then
          echo "Error: Linking PR to the issue failed."
          exit 1
        fi

    - name: Log PR and issue link result
      if: steps.link_pr_to_issue.outcome == 'success'
      run: echo "PR ${{ env.pr_number }} has been successfully linked to issue ${{ github.event.issue.number }}."

    - name: Retrieve the project ITEM_ID
      id: get_item_id
      run: |
        QUERY=$(cat <<EOF
        {
          "query": "{ repository(owner: \\"${{ github.repository_owner }}\\", name: \\"${{ github.event.repository.name }}\\") { issue(number: ${{ github.event.issue.number }}) { projectItems(first: 10) { nodes { id } } } } }"
        }
        EOF
        )
        echo "Sending query: $QUERY"

        RESPONSE=$(curl -X POST -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data "$QUERY" https://api.github.com/graphql)

        echo "GraphQL Response: $RESPONSE"
        ITEM_ID=$(echo "$RESPONSE" | jq -r '.data.repository.issue.projectItems.nodes[0].id')

        if [ -z "$ITEM_ID" ]; then
          echo "Error: Could not retrieve ITEM_ID"
          exit 1
        else
          echo "ITEM_ID=$ITEM_ID" >> $GITHUB_ENV
        fi

    - name: Retrieve the project FIELD_ID for "Status"
      id: get_field_id
      run: |
        QUERY=$(cat <<EOF
        {
          "query": "{ node(id: \\"PVT_kwHOAAMKjM4Ao-Sa\\") { ... on ProjectV2 { fields(first: 10) { nodes { ... on ProjectV2SingleSelectField { name id } } } } } }"
        }
        EOF
        )
        echo "Sending query: $QUERY"

        RESPONSE=$(curl -X POST -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data "$QUERY" https://api.github.com/graphql)

        echo "GraphQL Response: $RESPONSE"
        FIELD_ID=$(echo "$RESPONSE" | jq -r '.data.node.fields.nodes[] | select(.name == "Status").id')

        if [ -z "$FIELD_ID" ]; then
          echo "Error: Could not retrieve FIELD_ID for Status"
          exit 1
        else
          echo "FIELD_ID=$FIELD_ID" >> $GITHUB_ENV
        fi

    - name: Retrieve the "In Progress" option ID
      id: find_in_progress_tasks_id
      run: |
        QUERY=$(cat <<EOF
        {
          "query": "{ node(id: \\"PVT_kwHOAAMKjM4Ao-Sa\\") { ... on ProjectV2 { fields(first: 10) { nodes { ... on ProjectV2SingleSelectField { name options { id name } } } } } } }"
        }
        EOF
        )
        echo "Sending query: $QUERY"

        RESPONSE=$(curl -X POST -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data "$QUERY" https://api.github.com/graphql)

        echo "GraphQL Response: $RESPONSE"
        IN_PROGRESS_TASKS_ID=$(echo "$RESPONSE" | jq -r '.data.node.fields.nodes[] | select(.name == "Status") | .options[] | select(.name == "In Progress").id')

        if [ -z "$IN_PROGRESS_TASKS_ID" ]; then
          echo "Error: Could not retrieve 'In Progress' ID"
          exit 1
        else
          echo "IN_PROGRESS_TASKS_ID=$IN_PROGRESS_TASKS_ID" >> $GITHUB_ENV
        fi

    - name: Move task to "In Progress" column
      run: |
        QUERY=$(cat <<EOF
        {
          "query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \\"PVT_kwHOAAMKjM4Ao-Sa\\", itemId: \\"$ITEM_ID\\", fieldId: \\"$FIELD_ID\\", value: { singleSelectOptionId: \\"$IN_PROGRESS_TASKS_ID\\" } }) { projectV2Item { id } } }"
        }
        EOF
        )
        curl -X POST -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
        -H "Content-Type: application/json" \
        --data "$QUERY" \
        https://api.github.com/graphql

    - name: Log the project card movement result
      run: echo "Task successfully moved to 'In Progress' column."
