name: Assign Issue on Claim

on:
  issue_comment:
    types: [created]

jobs:
  claim_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Check if the comment contains "claim"
      if: contains(github.event.comment.body, 'claim')
      run: echo "Comment contains 'claim'. Proceeding with the assignment."

    - name: Check if issue is already assigned
      id: check_assignee
      run: |
        ASSIGNEES_COUNT=$(echo "${{ toJson(github.event.issue.assignees) }}" | jq length)
        if [ "$ASSIGNEES_COUNT" -gt 0 ]; then
          echo "Issue is already assigned."
          exit 0
        fi

    - name: Assign the issue to the commenter
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"assignees":["${{ github.event.comment.user.login }}"]}' \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}

    - name: Log the assignment result
      run: echo "Issue successfully assigned to ${{ github.event.comment.user.login }}."
