name: Propose PR

on:
  issue_comment:
    types: [created]

jobs:
  propose_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Comment is on a PR
        id: check_pr
        run: |
          if [[ -z "${{ github.event.issue.pull_request }}" ]]; then
            echo "This comment is not on a PR. Exiting."
            echo "is_pr=false" >> $GITHUB_OUTPUT
          else
            echo "This comment is on a PR."
            echo "is_pr=true" >> $GITHUB_OUTPUT
      - name: Parse Comment for Issue Number
        if: steps.check_pr.outputs.is_pr == 'true'
        id: parse_comment
        shell: bash
        run: |
          echo "Comment body: ${{ github.event.comment.body }}"
          if [[ "${{ github.event.comment.body }}" =~ propose\ PR\ \#([0-9]+) ]]; then
            echo "Issue number found: ${BASH_REMATCH[1]}"
            echo "issue_number=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "Comment does not match the required pattern."
            exit 1
      - name: Verify Issue Assignment
        if: steps.check_pr.outputs.is_pr == 'true'
        id: check_assignee
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = parseInt('${{ steps.parse_comment.outputs.issue_number }}');
            const commenter = '${{ github.event.comment.user.login }}';
            const { data: issue } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });
            const isAssigned = issue.assignees.some(assignee => assignee.login === commenter);
            core.setOutput('assigned', isAssigned);
            if (isAssigned) {
              console.log(`User ${commenter} is assigned to issue #${issueNumber}.`);
            } else {
              console.log(`User ${commenter} is NOT assigned to issue #${issueNumber}.`);
            }
      - name: Link PR to Issue
        if: steps.check_pr.outputs.is_pr == 'true' && steps.check_assignee.outputs.assigned == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = ${{ github.event.issue.number }};
            const issueNumber = parseInt('${{ steps.parse_comment.outputs.issue_number }}');
            const { data: pr } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            let prBody = pr.body || '';
            const fixText = `Fixes #${issueNumber}`;
            if (!prBody.includes(fixText)) {
              prBody += `\n\n${fixText}`;
              await github.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                body: prBody,
              });
              console.log(`Updated PR #${prNumber} to link to issue #${issueNumber}.`);
            } else {
              console.log(`PR #${prNumber} already links to issue #${issueNumber}.`);
            }
      - name: Notify User if Not Assigned
        if: steps.check_pr.outputs.is_pr == 'true' && steps.check_assignee.outputs.assigned == 'false'
        run: |
          echo "User is not assigned to issue #${{ steps.parse_comment.outputs.issue_number }}. No action taken."
